#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ndp
#
# IDENTIFICATION
#    src/backend/storage/ndp/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/ndp
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ndp_dirty_bufid.o ndp_support.o ndp_support_hash.o ndp_snapshot_info.o ndp_table_info.o ndp_version_index_cache.o ndp_functions.o

include $(top_srcdir)/src/backend/common.mk
