#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/vi
#
# IDENTIFICATION
#    src/backend/storage/vi/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/vi
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = vi.o vi_buf.o vi_bufpage.o vi_hash.o vi_writer.o

include $(top_srcdir)/src/backend/common.mk
